function(target_enable_lto target enable)
  if(NOT ${ENABLE})
    return()
  endif()
  include(CheckIPOSupported)
  check_ipo_supported(RESULT result OUTPUT output)

  if(result)
    message(STATUS "IPO/LTO is supported!")
    set_property(TARGET ${TARGET} PROPERTY INTERPROCEDURAL_OPTIMIZATION ${ENABLE})
  else()
    message(STATUS "IPO/LTO not supported!")
  endif()
endfunction()